import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "../components/TopBar";
import SideBar from "../components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-w-full min-h-screen  h-screen overflow-hidden text-black bg-blue-100">
          <TopBar />
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
