apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-secondary
  labels:
    app: mongodb
spec:
  serviceName: "mongodb-secondary"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      role: secondary
  template:
    metadata:
      labels:
        app: mongodb
        role: secondary
    spec:
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:5.0
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGODB_ADVERTISED_HOSTNAME
          value: mongodb-secondary
        - name: MONGODB_REPLICA_SET_MODE
          value: secondary
        - name: MONGODB_INITIAL_PRIMARY_HOST
          value: mongodb-primary
        - name: MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
          value: password123
        - name: MONGODB_REPLICA_SET_KEY
          value: replicasetkey123
        volumeMounts:
        - name: mongodb-data
          mountPath: /bitnami/mongodb
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-secondary
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
    role: secondary
